config/routes.rb
Rails.application.routes.draw do
  resources :forms
  resources :parttimes

  root 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  get 'login',      to: 'sessions#new'
  post 'login',     to: 'sessions#create'
  post 'logout',    to: 'sessions#logout'
  get 'welcome',    to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  get 'partprofile',to: 'users#partprofile'
  post 'partprofile',to: 'users#createpartprofile'

  get 'fullprofile',to: 'users#fullprofile'
  post 'fullprofile',to: 'users#createfullprofile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fullprofile.rb
class Fullprofile < ApplicationRecord
end

app/models/fulltimeform.rb
class Fulltimeform < ApplicationRecord
end

app/models/partprofile.rb
class Partprofile < ApplicationRecord
end

app/models/parttimeform.rb
class Parttimeform < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?
    helper_method :current_user_name
    def current_user    
        User.find_by(id: session[:user_id])  
    end
    def current_user_name
        user = current_user
        case user.typed
        when "parttime"
            Partprofile.find_by(username: user.username).name
        when "fulltime"
            Fullprofile.find_by(username: user.username).name
        end
    end
    def logged_in?
       
        !current_user.nil?
    end
    def authorized
        redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
    def new
        @form = Fulltimeform.new
    end
    def index
        @form = Fulltimeform.where(name: current_user.username)
    end
    def create
        @form = Fulltimeform.new (params.require(:form).permit(:name,:date,:content,:income))
        if @form.save
            redirect_to new_form_url
        else
            render :new
        end
    end
end

app/controllers/parttimes_controller.rb
class ParttimesController < ApplicationController
    def new
        @form = Fulltimeform.new
    end
    def index
        @form = Parttimeform.where(name: current_user.username)
    end
    def create
        @form = Parttimeform.new (params.require(:form).permit(:name,:date,:customer,:income,:description,:note))
        if @form.save
            redirect_to new_parttime_url
        else
            render :new
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.password === params[:password]
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to '/login'
    end
  end
  def logout
      session[:user_id] = nil
      redirect_to '/welcome'
  end

  def login
  end

  def welcome
  end
  def page_requires_login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
  end
  def partprofile

  end
  def createpartprofile
    @partprofile = Partprofile.new(params.require(:form).permit(:name,:time,:job))
    @partprofile.username = current_user.username
    @partprofile.save
    redirect_to '/welcome'
  end
  def fullprofile

  end
  def createfullprofile
    @fullprofile = Fullprofile.new(params.require(:form).permit(:name,:company,:taxcode,:address,:position))
    @fullprofile.username = current_user.username
    @fullprofile.save
    redirect_to '/welcome'
  end
  def create
    if !User.find_by(username: params[:user][:username])
      @user = User.create(params.require(:user).permit(:username,:password,:typed))
      session[:user_id] = @user.id

      case current_user.typed
      when "parttime"
        redirect_to partprofile_path
      when "fulltime"
        redirect_to fullprofile_path
      end
    else
      redirect_to new_user_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/parttimes_helper.rb
module ParttimesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/index.html.erb
<% if !@form.name[0].nil? %>
  <h1>List form</h1>
  <table>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>date</th>
      <th>content</th>
      <th>income</th>
    </tr>
  
    <% @form.each do |form| %>
      <tr>
        <td><%= form.id %></td>
        <td><%= form.name %></td>
        <td><%= form.date %></td>
        <td><%= form.content %></td>
        <td><%= form.income %></td>
      </tr>
    <% end %>
  </table>
<% end %> 
<p>
  <%= link_to 'add', new_form_url %>
</p>
<p>
  <%= link_to 'Home', welcome_path, method: :get %>
<p>

app/views/forms/new.html.erb
<H1> New fulltime form </H1>
<%= form_with scope: :form,url: forms_path, local: true do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
   
    <p>
        <%= form.label :Date %><br>
        <%= form.text_field :date %>
    </p>
    <p>
        <%= form.label :Content %><br>
        <%= form.text_field :content %>
    </p>
    <p>
        <%= form.label :income %><br>
        <%= form.text_field :income%>
    </p>
    <p>
      <%= form.submit "add"%>    

    </p>
    <p>
        <%= link_to 'Show', forms_path %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parttimes/index.html.erb
<% if !@form.name[0].nil? %>
  <h1>List Parttime form</h1>
  <table>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>date</th>
      <th>customer</th>
      <th>income</th>
      <th>note</th>
    </tr>
  
    <% @form.each do |form| %>
      <tr>
        <td><%= form.id %></td>
        <td><%= form.name %></td>
        <td><%= form.date %></td>
        <td><%= form.customer %></td>
        <td><%= form.income %></td>
        <td><%= form.note %></td>
      </tr>
    <% end %>
  </table>
 <% end %> 
<br>
<%= link_to 'Add', new_parttime_url %>
<p>
  <%= link_to 'Home', welcome_path, method: :get %>
<p>

app/views/parttimes/new.html.erb
<H1> New Parttime form </H1>
<%= form_with scope: :form,url: parttimes_path, local: true do |form| %>
    <p>
      <%= form.label :Name %><br>
      <%= form.text_field :name %>
    </p>
   
    <p>
        <%= form.label :Date %><br>
        <%= form.text_field :date %>
    </p>
    <p>
        <%= form.label :Customer %><br>
        <%= form.text_field :customer %>
    </p>
    <p>
        <%= form.label :Description %><br>
        <%= form.text_field :description %>
    </p>
    <p>
        <%= form.label :Income %><br>
        <%= form.text_field :income%>
    </p>
        <p>
        <%= form.label :Note %><br>
        <%= form.text_field :note%>
    </p>
    <p>
      <%= form.submit "add"%>    

    </p>
    <p>
        <%= link_to 'Show', parttimes_path %>
    </p>
  <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/fullprofile.html.erb
<h1><%=current_user.typed%> profile</h1>
<h2> Userame: <%= current_user.username%></h2>
<%= form_with scope: :form,url: fullprofile_path, local: true do |form| %>
    <p>
        <%= form.label :Name %><br>
        <%= form.text_field :name %>
    </p>
    <p>
    <%= form.label :Company %><br>
    <%= form.text_field :company %>
  </p>
 
  <p>
      <%= form.label :TaxCode %><br>
      <%= form.text_field :taxcode %>
  </p>
  <p>
      <%= form.label :Address %><br>
      <%= form.text_field :address %>
  </p>
  <p>
      <%= form.label :Position %><br>
      <%= form.text_field :position %>
  </p>
  <p>
    <%= form.submit "Save"%>    
  </p>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <p>
    <%= f.label :username, :id => "name"%>
    <%= f.text_field :username%>
  </p>
  
  <p>
    <%= f.label :password%>
    <%= f.password_field :password%>
  </p>

  <p>
    <%= f.label :type%>
    <%= f.select :typed,[["fulltime"],["parttime"]]%>
  </p>
  <%= f.submit %>
<%end%>
<p>
  <%= link_to 'Back', welcome_path, method: :get %>
<p>

app/views/users/partprofile.html.erb
<h1><%=current_user.typed%> profile</h1>
<h2> Userame: <%= current_user.username%></h2>
<%= form_with scope: :form,url: partprofile_path, local: true do |form| %>
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
      <%= form.label :Time %><br>
      <%= form.text_field :time %>
  </p>
  <p>
      <%= form.label :Job %><br>
      <%= form.text_field :Job %>
  </p>

  <p>
    <%= form.submit "add"%>    
  </p>

<% end %>